// All player-visible strings live here (game-design-system §10.3).
// Switching language is a data change, never a code change.
export const STR = {
  title: 'THE USELESS FISH',
  subtitle: 'the ocean sunfish · Mola mola',
  credit: 'made with love by Pukking Dragon',

  tapToStart: 'tap · click · press to begin',
  dragHint: 'Drag anywhere to swim — flick to dash',
  keyHint: 'or use WASD / arrows / a gamepad stick',

  goalAtlantic: 'ATLANTIC',
  goalPacific: 'PACIFIC',

  hudEggs: 'eggs',
  hudBest: 'furthest',
  hudPoints: 'points',
  hudPlankton: 'plankton',
  layPrompt: 'CLICK / TAP as fast as you can!',
  layEffort: 'FRENZY',
  cpLay: 'laying a clutch…',
  checkpointHit: 'CHECKPOINT!',

  // shop
  shopTitle: 'Tide-Pool Outfitters',
  shopBlurb: 'Spend hard-won eggs. Become a marginally less useless fish.',
  shopBack: 'back',
  shopMaxed: 'MAXED',
  shopBanked: 'in the purse',
  shopCantAfford: 'not enough eggs',

  // wardrobe + loot
  wardrobeTitle: 'The Wardrobe',
  wardrobeBlurb: 'Every fish deserves an outfit it did not earn.',
  wardrobeEquip: 'equip',
  wardrobeEquipped: 'worn',
  wardrobeLocked: '???',
  lootTitle: 'Crack a Mystery Clam',
  lootBlurb: (c) => `A clam of dubious provenance. ${c} eggs.`,
  lootOpen: 'crack it open',
  lootAgain: 'crack another',
  lootEquipNow: 'wear it',
  lootDupe: (n) => `Already owned — refunded ${n} eggs`,
  lootGot: 'a new look!',
  lootNeed: 'not enough eggs',

  caught: 'CAUGHT IN A NET!',
  grabbed: 'GRABBED!',
  struggle: 'WIGGLE! drag back and forth!',
  boostGet: (n) => `${n}!`,
  statusSlow: 'slowed',
  statusPoison: 'poisoned',
  statusHeal: 'mending',
  statusSwift: 'swift',
  statusShield: 'shielded',
  statusWounded: 'wounded',

  intro: {
    egg: 'a single, hopeful egg…',
    hatch: 'you hatch — small, soft, and clueless',
    siblings: 'you and your sibling drift out together',
    loss: 'the sea takes your sibling.\nyou swim on, alone.',
    skip: 'tap to skip',
  },
  deathSink: 'down you go…',

  zoneEnter: (n) => n,
  checkpoint: (n) => `${n} — checkpoint reached`,

  // multiple endings, chosen from how the run went
  endings: {
    plain:     { title: 'YOU MADE IT.',            line: 'Against all reason, the useless fish crosses an ocean.' },
    perfect:   { title: 'NOT A SCRATCH.',          line: 'A flawless crossing by the sea’s least likely athlete.' },
    battered:  { title: 'BATTERED, BUT HOME.',     line: 'Scarred, exhausted, and somehow still drifting.' },
    bountiful: { title: 'A MILLION USELESS BABIES.', line: 'Your clutch scatters into the blue. Most won’t make it — a few just might.' },
  },
  eggsLaid: (n) => `${n.toLocaleString()} eggs drift into the blue`,
  lifetimeEggs: (n) => `${n.toLocaleString()} eggs laid across all your lifetimes`,
  didYouKnow: 'did you know?',

  deaths: [
    'A sea lion had a snack. You were the snack.',
    'Splat. Rocks: 1, Fish: 0.',
    'Caught, hauled up, and deeply confused.',
    'The propeller did propeller things.',
    'Stung silly by a drifting jelly.',
    'You simply gave up. Understandable.',
    'A shark introduced itself. Briefly.',
    'An anglerfish’s little lamp was the last thing you saw.',
    'You hugged a sea mine. It hugged back.',
    'Sat on an urchin. A pointed lesson.',
    'A squid wanted a cuddle. Forever.',
    'A barracuda was simply faster than you.',
    'A blue shark made a common meal of you.',
    'A swordfish ran you clean through.',
    'A cookiecutter shark took one scoop too many.',
    'An orca played with its food. You were the food.',
    'Drained dry by freeloading copepods.',
    'You ate a plastic bag. It did not agree with you.',
  ],
  deathTitle: 'A USELESS END',
  retry: 'try again',
  toShop: 'upgrades',
  toWardrobe: 'wardrobe',
  toLoot: 'clams',
  continueBtn: (n) => `revive · ${n} eggs`,
  continueFree: 'revive · free (second wind)',

  distance: (m) => `${Math.round(m).toLocaleString()} m`,
  paused: 'paused',
  muted: 'sound off',
  unmuted: 'sound on',
  rotate: 'Turn your device — this fish prefers landscape.',

  // real ocean-sunfish facts — useless-looking, secretly amazing
  funFacts: [
    'The ocean sunfish (Mola mola) is the heaviest bony fish on Earth — up to 1,000 kg.',
    'It eats mostly jellyfish, which are about 95% water — so it dines on almost nothing.',
    'A female can release up to 300 million eggs at once — more than any other vertebrate.',
    'Newborn sunfish are about 2.5 mm long and grow up to 60 million times their birth weight.',
    'It has no real tail — just a frilly rudder called a clavus. That’s why steering is so clumsy.',
    'It basks on its side at the surface to rewarm after deep, cold dives past 600 m.',
    'Seabirds and cleaner fish pick parasites off its skin — it can carry dozens of species.',
    'Sailors called it the “swimming head” — a fish that looks like it forgot to grow a body.',
    'Useless-looking, but it dives over 800 m and crosses entire oceans. A secretly mighty icon.',
    'Its thick, rubbery skin can be several cm deep — hard for many predators to bite through.',
  ],
};
